---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/ottodevc/public_html/
    - /bin/cp  index.php $DEPLOYPATH   
    - /bin/cp -R vistas/ $DEPLOYPATH   
    - /bin/cp -R modelos $DEPLOYPATH   
      
